### ISSUE TITLE
Question about GAL Channel

### ISSUE THREAD

**Issue by Maxym77** [o-gs/DJI_FC_Patcher#10]
Hi !
I see in this screenshot of GNSS Application,
the GAL Channels are 4 and 8
Why you use 8 and 10 ?

![image](https://user-images.githubusercontent.com/9340420/44948078-b3debd00-ae17-11e8-9993-54375cc05a38.png)

**Comment by Matioupi** [comment]
4 and 8 are the defaults settings.
the first one in the minimum number of channels reserved for searching/tracking a galileo sat. The second one is the maximum.
Ublox M8 is capable of 32 channels in total.
Now that Galileo is reaching a higher number of available sats, I believe it's better to increase the min/max allowed.
