### ISSUE TITLE
" error: device not found"

### ISSUE THREAD

**Issue by peter12545** [o-gs/DJI_FC_Patcher#13]
I have root   phantom4 and phantom 4pro+2.0 by DUMLRacer.jar.  and import“adb shell” in platform
But it shows" error: device not found"
I try every method from google .It does not work

**Comment by Matioupi** [comment]
If you're trying to apply this guide/mods to a P4Pro+ v2.0 as i'm understanding you do, then you are on your own.

The readme.me clearly states the list of models it applies too, and P4P v2 or P4P+ v2 are NOT part of that list.

From the skill level I can foresee through your messages, you'll most likely brick your bird if you keep on...
