### ISSUE TITLE
Answer about  03.02.44.XX progress

### ISSUE THREAD

**Issue by Maxym77** [o-gs/DJI_FC_Patcher#2]
Hi! i follow the procedure and is perfect!
My answer is: how to rollback to original  03.02.44.07 ?
Flash normal firmware 01.04.0300 with Assist 2 after your procedure (actually is  03.02.44.08) ?

**Comment by Matioupi** [comment]
Flash full stock firmware image with DUMLDore v3 (avoid DJI assistant as 
much as you can)

only the 305/306 modules will be changed (all others are untouched) so 
it should only last a few minutes.

Le 26/08/2018 à 15:56, Maxym77 a écrit :
