### ISSUE TITLE
I get stuck at step 10

### ISSUE THREAD

**Issue by peter12545** [o-gs/DJI_FC_Patcher#8]
It shows No such file or directory;
![qq 20180901170611](https://user-images.githubusercontent.com/38899263/44944450-62c7cc80-ae09-11e8-8d51-d627772dabd4.png)

**Comment by Matioupi** [comment]
from the output you are showing some path is still referencing "my installation" : Mathieu/Dev/...

**Comment by lenisko** [comment]
@peter12545 Pull latest version of repo and check https://github.com/o-gs/DJI_FC_Patcher/blob/ba68146fa9d93489587f1f1c6f9b817efb35a825/Readme.md#9-export-path_to_tools-variable or just use `run_me.py` tool.

**Comment by peter12545** [comment]
THX, matioupi ,lenisko I have solved this problem.
